version: 2
jobs:
  machine:
    services:
      - docker
  build:
    docker:
      - image: 030735432563.dkr.ecr.us-east-2.amazonaws.com/circleci:latest
    steps:
      - checkout
      - run: docker run -d -p 8080:8080 --name circleci 030735432563.dkr.ecr.us-east-2.amazonaws.com/circleci:latest; sleep 10
      - run: curl --retry 10 --retry-delay 5 localhost:8080 | grep "Hello World!"
  deploy:
    docker:
      - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
    steps:
      - run: echo "deploy"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
